# Generated by Django 3.0.8 on 2020-07-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default='', max_length=8192),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientname',
            name='name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
