# Generated by Django 3.0.8 on 2020-07-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0002_auto_20200717_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
