# Generated by Django 3.0.8 on 2020-07-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0004_auto_20200718_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='in_products',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='in_products',
            field=models.ManyToManyField(related_name='ingredients', to='topical.Product'),
        ),
    ]
