# Generated by Django 3.0.8 on 2020-07-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0005_auto_20200718_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.IntegerField(null=True),
        ),
    ]
