# Generated by Django 3.0.8 on 2020-07-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0006_auto_20200718_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientname',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
