# Generated by Django 3.0.8 on 2020-07-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0009_auto_20200721_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
