# Generated by Django 3.0.8 on 2020-07-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0011_auto_20200723_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, default='', max_length=8192),
            preserve_default=False,
        ),
    ]
