# Generated by Django 3.0.8 on 2020-07-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0012_auto_20200724_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='excluded_ingredients',
            field=models.ManyToManyField(default=None, null=True, related_name='excluded_by', to='topical.Ingredient'),
        ),
    ]
