# Generated by Django 3.0.8 on 2020-07-24 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0012_auto_20200724_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='excluded_ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='excluded_by',
            field=models.ManyToManyField(blank=True, related_name='excluded_ingredients', to=settings.AUTH_USER_MODEL),
        ),
    ]
