# Generated by Django 3.0.8 on 2020-07-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0013_auto_20200724_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='excluded_ingredients',
            field=models.ManyToManyField(blank=True, default=None, related_name='excluded_by', to='topical.Ingredient'),
        ),
    ]
