# Generated by Django 3.0.8 on 2020-07-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0014_auto_20200724_1718'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='excluded_ingredients',
            field=models.ManyToManyField(blank=True, related_name='excluded_by', to='topical.Ingredient'),
        ),
    ]
