# Generated by Django 3.0.8 on 2020-07-24 22:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0015_auto_20200724_1825'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='excluded_ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='excluded_by',
            field=models.ManyToManyField(blank=True, related_name='excluded_ingredients', to=settings.AUTH_USER_MODEL),
        ),
    ]
