# Generated by Django 3.0.8 on 2020-07-24 18:28

from django.db import migrations
import topical.models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0015_auto_20200724_1825'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', topical.models.UserManager()),
            ],
        ),
    ]
