# Generated by Django 3.0.8 on 2020-07-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0015_auto_20200727_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('products', models.ManyToManyField(blank=True, related_name='tags', to='topical.Product')),
            ],
        ),
    ]
