# Generated by Django 3.0.8 on 2020-07-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0018_auto_20200728_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_setup',
            field=models.BooleanField(default=False),
        ),
    ]
