# Generated by Django 3.0.8 on 2020-07-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0019_auto_20200728_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientTagDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_stats', to='topical.Ingredient', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientTagEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshed', models.DateTimeField(auto_now=True)),
                ('total', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topical.Tag')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topical.IngredientTagDict')),
            ],
        ),
    ]
