# Generated by Django 3.0.8 on 2020-07-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0021_auto_20200729_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttagentry',
            name='refreshed',
            field=models.DateTimeField(default=None),
        ),
    ]
