# Generated by Django 3.0.8 on 2020-07-29 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0022_auto_20200729_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttagdict',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag_stats', to='topical.Ingredient'),
        ),
    ]
