# Generated by Django 3.0.8 on 2020-07-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0024_auto_20200729_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttagentry',
            name='upper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_tag', to='topical.IngredientTagDict'),
        ),
    ]
