# Generated by Django 3.0.8 on 2020-07-30 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0025_auto_20200729_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='excluded_by',
        ),
        migrations.CreateModel(
            name='ExclusionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=8192)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_profiles', to=settings.AUTH_USER_MODEL)),
                ('enabled', models.ManyToManyField(blank=True, related_name='profiles', to=settings.AUTH_USER_MODEL)),
                ('excluded_ingredients', models.ManyToManyField(blank=True, related_name='excluded_by', to='topical.Ingredient')),
                ('subscribers', models.ManyToManyField(related_name='all_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
