# Generated by Django 3.0.8 on 2020-08-01 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('topical', '0026_auto_20200730_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusionprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
